---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
     - name: Provision of a instances
       ec2:
         instance_type: t2.micro
         keypair: 'devops-jenkins-ansible-srv-key'
         group: 'Demo-SG'
         ec2_region: 'us-east-1'
         image: "ami-08111162"
         wait: true
         count: 1
         instance_tags:
            Name: Demo
       register: ec2
     - name: Add new instance to host group
       local_action: add_host hostname={{item.public_ip}} groupname=launched ansible_ssh_private_key_file=~/devops-jenkins-ansible-srv-key.pem
       with_items: ec2.instances
     - name: Wait for SSH to come up
       local_action: wait_for host={{item.public_dns_name}} port=22 delay=120 timeout=600 state=started
       with_items: "{{ ec2.instances }}"

- name: Install software
  hosts: launched
  gather_facts: true
  user: ec2-user
  sudo: yes
  tasks:
    - name: upgrade all packages
      yum: name=* state=latest
    - name: install the latest version of Docker
      yum: name=docker-io state=latest
    - name: (Enable it on System Boot)
      service: name=docker enabled=yes
    - name: ensure docker is running
      service:
        name: docker
        state: started
    - name: Add docker credentials for ec2-user user
      copy: src=/var/lib/jenkins/.docker/config.json dest=/home/ec2-user/.docker/config.json
    - name: Pull docker image
      shell: docker pull khandu443/ngclassifieds
    - name: Tag docker image 
      shell: docker tag khandu443/ngclassifieds demo
    - name: Run Docker image
      shell: docker -dit -p 80:80 demo
